services:
  - type: web
    name: lexi-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_token_here
      - key: SUPABASE_URL
        value: your_url_here
      - key: SUPABASE_KEY
        value: your_key_here